# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masterpeices.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon('evil.png'))
        MainWindow.showMaximized()
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 480, 900))
        self.widget.setStyleSheet("QWidget#widget{border:2px solid black;\n"
"border-radius:10px;background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(239, 197, 204, 255), stop:1 rgba(255, 255, 255, 255))}\n"
"")
        self.widget.setObjectName("widget")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(20, 580, 430, 260))
        self.widget_4.setStyleSheet("QWidget#widget_4{border:2px solid black;\n"
"border-radius:10px}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 200, 50))
        self.label_2.setStyleSheet("font: 10pt \"Franklin Gothic Demi\";\n"
"font: 700 12pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 61, 21))
        self.label_3.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:green;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setGeometry(QtCore.QRect(50, 130, 120, 21))
        self.label_4.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:red")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setGeometry(QtCore.QRect(50, 170, 130, 21))
        self.label_6.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:orange")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setGeometry(QtCore.QRect(130, 90, 100, 21))
        self.label_5.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:green;")
        self.label_5.setObjectName("label_5")
        self.die_update = QtWidgets.QLabel(self.widget_4)
        self.die_update.setGeometry(QtCore.QRect(112, 130, 91, 21))
        self.die_update.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:red")
        self.die_update.setObjectName("die_update")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setGeometry(QtCore.QRect(160, 170, 100, 21))
        self.label_13.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:orange")
        self.time_update = QtWidgets.QLabel(self.widget_4)
        self.time_update.setGeometry(QtCore.QRect(130, 220, 130, 21))
        self.time_update.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
                                   "color:black")
        self.time_update.setObjectName("time_update")

        self.label_13.setObjectName("label_13")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(20, 10, 430, 380))
        self.widget_5.setStyleSheet("QWidget#widget_5{border:2px solid black;\n"
"border-radius:10px}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.label_36 = QtWidgets.QLabel(self.widget_5)
        self.label_36.setGeometry(QtCore.QRect(120, 20, 210, 30))
        self.label_36.setStyleSheet("font: 10pt \"Franklin Gothic Demi\";\n"
"font: 700 12pt \"Segoe UI\";")
        self.label_36.setObjectName("label_36")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 190, 120,43 ))
        self.pushButton_5.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_37 = QtWidgets.QLabel(self.widget_5)
        self.label_37.setGeometry(QtCore.QRect(30, 200, 71, 31))
        self.label_37.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color:Black;")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.widget_5)
        self.label_38.setGeometry(QtCore.QRect(130, 200, 70, 31))
        self.label_38.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:Black;")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.widget_5)
        self.label_39.setGeometry(QtCore.QRect(30, 250, 350, 20))
        self.label_39.setStyleSheet("font: 8pt \"Segoe UI\";")
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.widget_5)
        self.label_40.setGeometry(QtCore.QRect(30, 300, 180, 31))
        self.label_40.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color:green;")
        self.label_40.setObjectName("label_40")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 300, 120, 40))
        self.pushButton_6.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_42 = QtWidgets.QLabel(self.widget_5)
        self.label_42.setGeometry(QtCore.QRect(30, 140, 100, 31))
        self.label_42.setStyleSheet("font: 700 11pt \"Segoe UI\";\n"
"color:Black;")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.widget_5)
        self.label_43.setGeometry(QtCore.QRect(130, 140, 100, 31))
        self.label_43.setStyleSheet("font: 700 10pt \"Segoe UI\";\n"
"color:Black;")
        self.label_43.setObjectName("label_43")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 140, 120, 40))
        self.pushButton_7.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_44 = QtWidgets.QLabel(self.widget_5)
        self.label_44.setGeometry(QtCore.QRect(30, 60, 150, 31))
        self.label_44.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"color:Black;")
        self.label_44.setObjectName("label_44")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 60, 120, 38))
        self.pushButton_8.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox = QtWidgets.QComboBox(self.widget_5)
        self.comboBox.setGeometry(QtCore.QRect(300, 22, 110, 30))
        self.comboBox.setStyleSheet("border:3px solid black")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(20, 400, 430, 170))
        self.widget_3.setStyleSheet("QWidget#widget_3{border:2px solid black;\n"
"border-radius: 10px;}")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(100, 30, 190, 25))
        self.label.setStyleSheet("font: 10pt \"Franklin Gothic Demi\";\n"
"font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.start = QtWidgets.QPushButton(self.widget_3)
        self.start.setGeometry(QtCore.QRect(40, 80, 120, 50))
        self.start.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.start.setObjectName("start")
        self.stop = QtWidgets.QPushButton(self.widget_3)
        self.stop.setGeometry(QtCore.QRect(250, 80, 120, 50))
        self.stop.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;\n"
"font: 700 10pt \"Segoe UI\";\n"
"background-color:rgb(0, 255, 255)")
        self.stop.setObjectName("stop")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(500, 20, 1400, 900))
        self.widget_2.setStyleSheet("QWidget#widget_2{border:2px solid black;\n"
"border-radius:10px;background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(239, 197, 204, 255), stop:1 rgba(255, 255, 255, 255))}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 50, 1360, 830))
        self.tableWidget.setStyleSheet("border:2px solid black;\n"
"border-radius:10px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        item.setIcon(icon)
        item.setBackground(QtGui.QColor(255, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_41 = QtWidgets.QLabel(self.widget_2)
        self.label_41.setGeometry(QtCore.QRect(600, 10, 280, 31))
        self.label_41.setStyleSheet("font: 10pt \"Franklin Gothic Demi\";\n"
"font: 700 12pt \"Segoe UI\";\n"
"border-radius:10px")
        self.label_41.setObjectName("label_41")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1287, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tableWidget.setColumnWidth(0, 100)
        self.tableWidget.setColumnWidth(1, 300)
        self.tableWidget.setColumnWidth(2, 300)
        self.tableWidget.setColumnWidth(3, 300)
        self.tableWidget.setColumnWidth(4, 300)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Store Checker-ADB"))
        self.label_2.setText(_translate("MainWindow", "Data Capture"))
        self.label_3.setText(_translate("MainWindow", "Live:"))
        self.label_4.setText(_translate("MainWindow", "Die:"))
        self.label_6.setText(_translate("MainWindow", "Recheck:"))
        self.time_update.setText(_translate("MainWindow", "00:00:00"))
        self.label_5.setText(_translate("MainWindow", "        0"))
        self.die_update.setText(_translate("MainWindow", "           0"))
        self.label_13.setText(_translate("MainWindow", "   0"))
        self.label_36.setText(_translate("MainWindow", "Data Settings"))
        self.pushButton_5.setText(_translate("MainWindow", "LoadProxy"))
        self.label_37.setText(_translate("MainWindow", "Proxy:"))
        self.label_38.setText(_translate("MainWindow", "  0"))
        self.label_39.setText(_translate("MainWindow", "(Open proxy.txt file in folder before loadproxy)"))
        self.label_40.setText(_translate("MainWindow", "Live Account"))
        self.pushButton_6.setText(_translate("MainWindow", "Get"))
        self.label_42.setText(_translate("MainWindow", "Devices:"))
        self.label_43.setText(_translate("MainWindow", "  0"))
        self.pushButton_7.setText(_translate("MainWindow", "GetDevice"))
        self.label_44.setText(_translate("MainWindow", "SQL Connect:"))
        self.pushButton_8.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "Control Devices"))
        self.start.setText(_translate("MainWindow", "Start All"))
        self.stop.setText(_translate("MainWindow", "Stop All"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Devices"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Proxy"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        self.label_41.setText(_translate("MainWindow", "       Devices Capture"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Walmart"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Target"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
